name: flutter_manga_reader

ide:
  intellij:
    enabled: false

packages:
  - packages/*
  - ./

scripts:
  gen-all:
    description: Run all code generation scripts
    run: melos run gen --no-select

  gen:
    description: Run build_runner to generate files
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

  pb-gen:
    description: Generate protobuf files
    run: protoc --dart_out=lib/gen -I=protos protos/*.proto

  clean-ios:
    run: rm -rf ios/Pods ios/Podfile.lock && flutter clean && flutter pub get
    packageFilters:
      scope:
        - flutter_manga_reader
