name: flutter_manga_reader
description: A cross-platform manga reader.
publish_to: "none"
homepage: https://github.com/TesteurManiak/flutter_manga_reader
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  background_downloader: ^8.0.5
  cached_network_image: ^3.3.1
  clock: ^1.1.1
  collection: ^1.18.0
  drift: ^2.14.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  http: ^1.1.2
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  manga_reader_core:
    path: packages/manga_reader_core
  mangadex:
    path: packages/mangadex
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.18
  theme_tailor_annotation: ^2.0.2
  url_launcher: ^6.2.2

dev_dependencies:
  alchemist: ^0.7.0
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  custom_lint: ^0.5.7
  drift_dev: ^2.14.1
  fd_lints: ^2.2.0
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  melos: ^3.4.0
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  theme_tailor: ^2.0.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
  fonts:
    - family: MangaReader
      fonts:
        - asset: assets/icons/MangaReader.ttf

# Check the package's documentation to setup the launcher icons
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/icon.png"
  min_sdk_android: 22
  adaptive_icon_background: "#0075ff"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/launcher_icons/icon.png"
  macos:
    generate: true
    image_path: "assets/launcher_icons/icon.png"

# Check the package's documentation to setup the splash screen
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_native_splash:
  color: "#0075ff"
  image: "assets/splash/splash.png"
  android_12:
    color: "#0075ff"
  web: false
