name: flutter_manga_reader
description: A cross-platform manga reader.
publish_to: "none"
homepage: https://github.com/TesteurManiak/flutter_manga_reader
version: 0.2.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

workspace:
  - packages/manga_reader_core
  - packages/mangabox
  - packages/mangadex
  - packages/xpath_selector
  - packages/xpath_selector_html_parser

dependencies:
  background_downloader: ^8.9.3
  cached_network_image: ^3.4.1
  clock: ^1.1.1
  collection: ^1.19.0
  drift: ^2.23.1
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  logging: ^1.3.0
  manga_reader_core:
    path: packages/manga_reader_core
  mangabox:
    path: packages/mangabox
  mangadex:
    path: packages/mangadex
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  protobuf: ^3.1.0
  riverpod_annotation: ^2.6.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.5
  sqlite3_flutter_libs: ^0.5.29
  theme_tailor_annotation: ^3.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  alchemist: ^0.11.0
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  build_version: ^2.1.1
  custom_lint: ^0.7.0
  drift_dev: ^2.23.1
  fd_lints: ^2.3.1
  flutter_gen_runner: ^5.8.0
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.3
  json_serializable: ^6.9.0
  melos: ^6.3.2
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  theme_tailor: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
  fonts:
    - family: MangaReader
      fonts:
        - asset: assets/icons/MangaReader.ttf

# Check the package's documentation to setup the launcher icons
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_launcher_icons:
  image_path: "assets/launcher_icons/icon.png"
  android: "ic_launcher"
  min_sdk_android: 22
  adaptive_icon_background: "#0075ff"
  ios: true
  image_path_ios_dark_transparent: "assets/launcher_icons/icon-transparent.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/launcher_icons/icon.png"

# Check the package's documentation to setup the splash screen
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_native_splash:
  color: "#0075ff"
  image: "assets/splash/splash.png"
  android_12:
    color: "#0075ff"
  web: false
