name: flutter_manga_reader
description: A cross-platform manga reader.
publish_to: "none"
homepage: https://github.com/TesteurManiak/flutter_manga_reader
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  background_downloader: ^7.8.1
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  collection: ^1.17.1
  drift: ^2.10.0
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  http: ^1.1.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  manga_reader_core:
    path: packages/manga_reader_core
  mangadex:
    path: packages/mangadex
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.15
  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  alchemist: ^0.6.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  custom_lint: ^0.4.0
  drift_dev: ^2.10.0
  fd_lints: ^2.0.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.3
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0
  theme_tailor: ^2.0.0

flutter:
  uses-material-design: true

# Check the package's documentation to setup the launcher icons
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/icon.png"
  min_sdk_android: 22
  adaptive_icon_background: "#0075ff"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/launcher_icons/icon.png"
  macos:
    generate: true
    image_path: "assets/launcher_icons/icon.png"

# Check the package's documentation to setup the splash screen
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_native_splash:
  color: "#0075ff"
  image: "assets/splash/splash.png"
  android_12:
    image: "assets/splash/splash.png"
    color: "#0075ff"
  web: false
