name: flutter_manga_reader
description: A cross-platform manga reader.
publish_to: "none"
homepage: https://github.com/TesteurManiak/flutter_manga_reader
version: 0.2.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  background_downloader: ^8.5.2
  cached_network_image: ^3.3.1
  clock: ^1.1.1
  collection: ^1.18.0
  drift: ^2.18.0
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.0
  logging: ^1.2.0
  manga_reader_core:
    path: packages/manga_reader_core
  mangabox:
    path: packages/mangabox
  mangadex:
    path: packages/mangadex
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  protobuf: ^3.1.0
  riverpod_annotation: ^2.3.5
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  sqlite3_flutter_libs: ^0.5.23
  theme_tailor_annotation: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  alchemist: ^0.7.0
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  custom_lint: ^0.6.4
  drift_dev: ^2.18.0
  fd_lints: ^2.3.0
  flutter_gen: ^5.5.0+1
  flutter_gen_runner: ^5.4.0
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  melos: ^6.0.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  theme_tailor: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
  fonts:
    - family: MangaReader
      fonts:
        - asset: assets/icons/MangaReader.ttf

# Check the package's documentation to setup the launcher icons
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/icon.png"
  min_sdk_android: 22
  adaptive_icon_background: "#0075ff"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/launcher_icons/icon.png"
  macos:
    generate: true
    image_path: "assets/launcher_icons/icon.png"

# Check the package's documentation to setup the splash screen
# https://pub.dev/packages/flutter_native_splash#1-setting-the-splash-screen
flutter_native_splash:
  color: "#0075ff"
  image: "assets/splash/splash.png"
  android_12:
    color: "#0075ff"
  web: false
