name: xpath_selector_html_parser
description: A html parser implementation with html for xpath_selector, xpath_selector is required.
version: 3.0.1
homepage: https://github.com/simonkimi/xpath_selector
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  xpath_selector:
    path: ../xpath_selector
  html: ^0.15.6

dev_dependencies:
  lints: ^6.0.0
