name: xpath_selector_html_parser
description: A html parser implementation with html for xpath_selector, xpath_selector is required.
version: 3.0.1
homepage: https://github.com/simonkimi/xpath_selector
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  xpath_selector:
    path: ../xpath_selector
  html: ^0.15.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
