name: manga_reader_core
description: Core package for manga reader.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_manga_reader
publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  clock:
  crypto: ^3.0.6
  freezed_annotation:
  html: ^0.15.6
  http: ^1.5.0
  json_annotation:
  xpath_selector_html_parser:
    path: ../xpath_selector_html_parser

dev_dependencies:
  build_runner:
  fd_lints:
  freezed:
  json_serializable:
