name: manga_reader_core
description: Core package for manga reader.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_manga_reader
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  crypto: ^3.0.5
  freezed_annotation: ^2.4.4
  html: ^0.15.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  xpath_selector_html_parser:
    path: ../xpath_selector_html_parser

dev_dependencies:
  build_runner: ^2.4.13
  fd_lints: ^2.3.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
