name: manga_reader_core
description: Core package for manga reader.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_manga_reader

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  fd_lints: ^2.1.0
  freezed: ^2.4.1
