name: mangabox
description: Wrapper for the Mangabox's websites.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_manga_reader
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  manga_reader_core:
    path: ../manga_reader_core

dev_dependencies:
  build_runner: ^2.4.13
  fd_lints: ^2.3.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
